### ISSUE TITLE
Need Help for DownloadRange2

### ISSUE THREAD

**Issue by b68h4** [codehaks/DownloadRangeDemo#1]
Hello @codehaks 

I read its code and I think it's the only example of range download I can find.

I am trying to integrate the code into my own project but did not get a successful result.

The program will take the file from Google Driveden and transfer it to the user.
I want to do this as range download.

I need your help.

**Comment by codehaks** [comment]
You can stream the file using MemoryStream Class

**Comment by b68h4** [comment]
> You can stream the file using MemoryStream Class

When a request is made to the api, it takes too long to transfer the file to memorystream
so it causes the user to wait.

While downloading the file from drive in parts, I also need to return to the user in parts.

**Comment by codehaks** [comment]
You can do this using Response Body, means you have to go one level deep than MVC itself, here is a sample code using SQLServer FileStream, you just have to replace SQL with the API

https://github.com/codehaks/MyUploadPage/blob/read-body-stream/MyUploadPage/Controllers/DocController.cs

**Comment by b68h4** [comment]
> Bunu Response Body kullanarak yapabilirsiniz, yani MVC'nin kendisinden bir seviye daha derine inmeniz gerekir, işte SQLServer FileStream kullanan bir örnek kod, sadece SQL'i API ile değiştirmeniz gerekir
> 
> https://github.com/codehaks/MyUploadPage/blob/read-body-stream/MyUploadPage/Controllers/DocController.cs

it's really close to what I'm looking for.
my code:

```
[HttpGet]
    [DisableRequestSizeLimit]
    public async Task<FileStreamResult> Download([FromQuery(Name = "file")] string fileid)
    {
        if (!string.IsNullOrEmpty(fileid))
        {
         
           
          
            var decoded = Base64.Base64Decode(fileid);
            var file = DriveAPI.service.Files.Get(decoded);
            file.SupportsAllDrives = true;
            file.SupportsTeamDrives = true;
           
            var fileinf = file.Execute();
            var filesize = fileinf.FileSize;

            var cli = new HttpClient(DriveAPI.service.HttpClient.MessageHandler);
            //var req = await cli.SendAsync(file.CreateRequest());

            var req = await cli.GetAsync($"https://www.googleapis.com/drive/v2/files/{decoded}?alt=media", HttpCompletionOption.ResponseHeadersRead);

            //var req = await DriveAPI.service.HttpClient.GetAsync($"https://www.googleapis.com/drive/v2/files/{decoded}?alt=media", HttpCompletionOption.ResponseHeadersRead);
            var contenttype = req.Content.Headers.ContentType.MediaType;

            if (contenttype == "application/json")
            {
                var message = JObject.Parse(req.Content.ReadAsStringAsync().Result).SelectToken("error.message");

                if (message.ToString() == "The download quota for this file has been exceeded")
                {
                    throw new Exception("Google Drive Günlük İndirme Kotası Aşıldı. Lütfen 24-48 Saat Sonra Tekrar Deneyin.");
                }
                else
                {
                    throw new Exception(message.ToString());
                }
            }
            else 
            {
               
                return File(req.Content.ReadAsStream(), contenttype, fileinf.OriginalFilename, false);
            }
        }
        else
        {
            return null;
        }
    }
```

**Comment by b68h4** [comment]
google drive api returns the file to me and simultaneously pass it to the user.

but I had to do this in byte-range form. Some of my friends gave me such advice.
Thus, the internet download manager or another type of program will both continue if the download is interrupted and will download quickly because it is downloading.
but I can't get some partial download from the api.
